### PR TITLE
Added a neat navbar and footer

### PR DESCRIPTION
**Pull request by PavvanPradeep**
i added a navbar and footer please check it out

### CODE REVIEW

**Comment by PavvanPradeep** [comment]
@ashwin3005 please review my pull request

**Comment by PavvanPradeep** [comment]
image

**Comment by PavvanPradeep** [comment]
image

**Comment by ashwin3005** [comment]
We don't need those many links in the footer..

Also currently we have nothing to navigate.

**Comment by PavvanPradeep** [comment]
@ashwin3005 so i'll remove all those links and keep the follow us part?

**Pull request closed without merging**
