### PR TITLE
refractor: Making src/*.js code more slimmer and simpler

### PR DESCRIPTION
**Pull request by MoonLGH**
## Checkmark
- [x] Tested

### List Changed
- deleting App.js and just move it to index.js
The purpose of App.js is only to render elements which imported from Textarea.js and got exported again so index.js can use it
now, why not just Render the Textarea.js within index.js
- make process in password.js faster by just randomizing it by its string
Because listOfTypes here string[], and word is a string because getting string from random, and technically, the word is string[] and we can directly just randomize from array of string

### CODE REVIEW

**Comment by ashwin3005** [comment]
Thanks a lot for your contribution.

**Comment by ashwin3005** [comment]
Can you explain the purpose of removing the App.js file?

**Comment by MoonLGH** [comment]
umm, why not let me ask you this,
why are you making a file (let's just call it file A) that just import from TextArea.js and export it, so another file (let's call it file B) can import from file A, that is just the same thing as importing TextArea.js directly to file B

**Comment by MoonLGH** [comment]
or like this

a.js
```
export const x ="hello world"
```
b.js
```
import x from "./a.js"
export x
```
c.js
```
import x from "./b.js"
//actually using the x here
```

then what the purposes of b.js if you can directly import from a.js

**Comment by ashwin3005** [comment]
oh, Now it's clear..

But why do they provide App.js by default in create-react-app?

**Comment by MoonLGH** [comment]
well, this is my assumption, app.js on create-react-app is used if you had more than 1 component to render, so if you had like component from, a b c d, you can mix them in app.js so index.js just import 1 component from app.js
but in this scenario, app.js only import 1 component, so why not just put it inside index.js

**Comment by ashwin3005** [comment]
Now It's clear.
 thank you..

**Pull request merged**
